"""add media_id to messages

Revision ID: 13dae2765953
Revises: f69ffbdeaea2
Create Date: 2026-07-28 23:38:17.949122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13dae2765953'
down_revision: Union[str, None] = 'f69ffbdeaea2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('media_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'messages', 'media', ['media_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'media_id')
    # ### end Alembic commands ###
