"""Fix all Features

Revision ID: 4c310e24a3ae
Revises: g7h8i9j0k1l2
Create Date: 2026-07-27 21:01:03.325672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c310e24a3ae'
down_revision: Union[str, None] = 'g7h8i9j0k1l2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('feed_positions_user_id_key'), 'feed_positions', type_='unique')
    op.create_unique_constraint('uq_feed_positions_user_feed_type', 'feed_positions', ['user_id', 'feed_type'])
    op.drop_index(op.f('ix_post_likes_post_id'), table_name='post_likes')
    op.drop_index(op.f('ix_post_likes_user_id'), table_name='post_likes')
    op.drop_constraint(op.f('uq_post_likes_user_post'), 'post_likes', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_post_likes_user_post'), 'post_likes', ['user_id', 'post_id'])
    op.create_index(op.f('ix_post_likes_user_id'), 'post_likes', ['user_id'], unique=False)
    op.create_index(op.f('ix_post_likes_post_id'), 'post_likes', ['post_id'], unique=False)
    op.drop_constraint('uq_feed_positions_user_feed_type', 'feed_positions', type_='unique')
    op.create_unique_constraint(op.f('feed_positions_user_id_key'), 'feed_positions', ['user_id'])
    # ### end Alembic commands ###
