"""Reels

Revision ID: 65d9d4fb08c3
Revises: 049363d7f880
Create Date: 2026-07-27 23:23:44.157072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65d9d4fb08c3'
down_revision: Union[str, None] = '049363d7f880'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('story_highlights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('cover_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('story_highlight_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('highlight_id', sa.UUID(), nullable=False),
    sa.Column('story_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['highlight_id'], ['story_highlights.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('story_reactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('story_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('emoji', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('story_replies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('story_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_album_photos_album_id'), table_name='album_photos')
    op.drop_index(op.f('ix_media_media_type'), table_name='media')
    op.drop_index(op.f('ix_media_user_id'), table_name='media')
    op.drop_index(op.f('ix_photo_albums_user_id'), table_name='photo_albums')
    op.drop_index(op.f('ix_reels_user_id'), table_name='reels')
    op.add_column('stories', sa.Column('music_url', sa.String(length=500), nullable=True))
    op.add_column('stories', sa.Column('music_name', sa.String(length=255), nullable=True))
    op.add_column('stories', sa.Column('music_artist', sa.String(length=255), nullable=True))
    op.add_column('stories', sa.Column('music_cover_url', sa.String(length=500), nullable=True))
    op.add_column('stories', sa.Column('is_close_friends_only', sa.Boolean(), nullable=True))
    op.drop_index(op.f('ix_stories_expires_at'), table_name='stories')
    op.drop_index(op.f('ix_stories_user_id'), table_name='stories')
    op.drop_index(op.f('ix_story_views_story_id'), table_name='story_views')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_story_views_story_id'), 'story_views', ['story_id'], unique=False)
    op.create_index(op.f('ix_stories_user_id'), 'stories', ['user_id'], unique=False)
    op.create_index(op.f('ix_stories_expires_at'), 'stories', ['expires_at'], unique=False)
    op.drop_column('stories', 'is_close_friends_only')
    op.drop_column('stories', 'music_cover_url')
    op.drop_column('stories', 'music_artist')
    op.drop_column('stories', 'music_name')
    op.drop_column('stories', 'music_url')
    op.create_index(op.f('ix_reels_user_id'), 'reels', ['user_id'], unique=False)
    op.create_index(op.f('ix_photo_albums_user_id'), 'photo_albums', ['user_id'], unique=False)
    op.create_index(op.f('ix_media_user_id'), 'media', ['user_id'], unique=False)
    op.create_index(op.f('ix_media_media_type'), 'media', ['media_type'], unique=False)
    op.create_index(op.f('ix_album_photos_album_id'), 'album_photos', ['album_id'], unique=False)
    op.drop_table('story_replies')
    op.drop_table('story_reactions')
    op.drop_table('story_highlight_items')
    op.drop_table('story_highlights')
    # ### end Alembic commands ###
