"""t1 to t10

Revision ID: 6fe5ce54febb
Revises: f0a1b2c3d4e5
Create Date: 2026-08-07 14:00:44.664504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fe5ce54febb'
down_revision: Union[str, None] = 'f0a1b2c3d4e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('content_events_client_event_id_key'), 'content_events', type_='unique')
    op.drop_index(op.f('ix_content_events_occurred_id'), table_name='content_events')
    op.drop_index(op.f('ix_posts_created_at'), table_name='posts')
    op.drop_index(op.f('ix_posts_privacy'), table_name='posts')
    op.drop_index(op.f('ix_posts_privacy_created_at'), table_name='posts')
    op.drop_index(op.f('ix_posts_trending_score'), table_name='posts')
    op.drop_index(op.f('ix_posts_user_id'), table_name='posts')
    op.drop_index(op.f('ix_user_interests_user_strength'), table_name='user_interests')
    op.drop_constraint(op.f('chk_users_username_format'), 'users', type_='check')
    op.drop_index(op.f('ix_view_sessions_content_completed'), table_name='view_sessions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_view_sessions_content_completed'), 'view_sessions', ['content_id', 'completed'], unique=False)
    op.create_check_constraint(op.f('chk_users_username_format'), 'users', "username IS NULL OR username::text ~ '^[a-zA-Z0-9_]+(?:\\.[a-zA-Z0-9_]+)*$'::text")
    op.create_index(op.f('ix_user_interests_user_strength'), 'user_interests', ['user_id', 'strength'], unique=False)
    op.create_index(op.f('ix_posts_user_id'), 'posts', ['user_id'], unique=False)
    op.create_index(op.f('ix_posts_trending_score'), 'posts', ['trending_score'], unique=False)
    op.create_index(op.f('ix_posts_privacy_created_at'), 'posts', ['privacy', 'created_at'], unique=False)
    op.create_index(op.f('ix_posts_privacy'), 'posts', ['privacy'], unique=False)
    op.create_index(op.f('ix_posts_created_at'), 'posts', ['created_at'], unique=False)
    op.create_index(op.f('ix_content_events_occurred_id'), 'content_events', ['occurred_at', 'id'], unique=False)
    op.create_unique_constraint(op.f('content_events_client_event_id_key'), 'content_events', ['client_event_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
