"""Error 404

Revision ID: 6ffd8d56a3e4
Revises: e39c7123ea1f
Create Date: 2026-07-28 22:12:52.239178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ffd8d56a3e4'
down_revision: Union[str, None] = 'e39c7123ea1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
