"""Post Background

Revision ID: 7a4abbf6d3b2
Revises: 043f56f083f6
Create Date: 2026-08-01 16:41:03.833206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a4abbf6d3b2'
down_revision: Union[str, None] = '043f56f083f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('background_style', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'background_style')
    # ### end Alembic commands ###
