"""Full Friends

Revision ID: a7d312d4ed9c
Revises: d0a82f745083
Create Date: 2026-08-02 19:56:33.718425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7d312d4ed9c'
down_revision: Union[str, None] = 'd0a82f745083'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('follow_requests', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_index('ix_follow_requests_requester_id', table_name='follow_requests')
    op.drop_index('ix_follow_requests_target_id', table_name='follow_requests')
    op.alter_column('mutes', 'mute_posts',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('mutes', 'mute_stories',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('mutes', 'mute_notes',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('mutes', 'mute_notifications',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_index('ix_mutes_muted_user_id', table_name='mutes')
    op.drop_index('ix_mutes_user_id', table_name='mutes')
    op.alter_column('privacy_settings', 'hide_last_seen',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('privacy_settings', 'hide_birthday',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('privacy_settings', 'hide_phone',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('privacy_settings', 'hide_email',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('privacy_settings', 'hide_work',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('privacy_settings', 'hide_education',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('privacy_settings', 'reel_privacy',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'everyone'::character varying"))
    op.alter_column('privacy_settings', 'photo_privacy',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'everyone'::character varying"))
    op.alter_column('privacy_settings', 'video_privacy',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'everyone'::character varying"))
    op.alter_column('privacy_settings', 'friend_request_permissions',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'everyone'::character varying"))
    op.alter_column('privacy_settings', 'message_permissions',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'everyone'::character varying"))
    op.alter_column('privacy_settings', 'call_permissions',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'everyone'::character varying"))
    op.alter_column('privacy_settings', 'hide_followers_list',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('privacy_settings', 'hide_following_list',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('privacy_settings', 'download_media_permissions',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'everyone'::character varying"))
    op.alter_column('privacy_settings', 'invite_permissions',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'everyone'::character varying"))
    op.drop_index('ix_restricts_restricted_user_id', table_name='restricts')
    op.drop_index('ix_restricts_user_id', table_name='restricts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_restricts_user_id', 'restricts', ['user_id'], unique=False)
    op.create_index('ix_restricts_restricted_user_id', 'restricts', ['restricted_user_id'], unique=False)
    op.alter_column('privacy_settings', 'invite_permissions',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'everyone'::character varying"))
    op.alter_column('privacy_settings', 'download_media_permissions',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'everyone'::character varying"))
    op.alter_column('privacy_settings', 'hide_following_list',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('privacy_settings', 'hide_followers_list',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('privacy_settings', 'call_permissions',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'everyone'::character varying"))
    op.alter_column('privacy_settings', 'message_permissions',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'everyone'::character varying"))
    op.alter_column('privacy_settings', 'friend_request_permissions',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'everyone'::character varying"))
    op.alter_column('privacy_settings', 'video_privacy',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'everyone'::character varying"))
    op.alter_column('privacy_settings', 'photo_privacy',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'everyone'::character varying"))
    op.alter_column('privacy_settings', 'reel_privacy',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'everyone'::character varying"))
    op.alter_column('privacy_settings', 'hide_education',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('privacy_settings', 'hide_work',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('privacy_settings', 'hide_email',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('privacy_settings', 'hide_phone',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('privacy_settings', 'hide_birthday',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('privacy_settings', 'hide_last_seen',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_index('ix_mutes_user_id', 'mutes', ['user_id'], unique=False)
    op.create_index('ix_mutes_muted_user_id', 'mutes', ['muted_user_id'], unique=False)
    op.alter_column('mutes', 'mute_notifications',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('mutes', 'mute_notes',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('mutes', 'mute_stories',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('mutes', 'mute_posts',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.create_index('ix_follow_requests_target_id', 'follow_requests', ['target_id'], unique=False)
    op.create_index('ix_follow_requests_requester_id', 'follow_requests', ['requester_id'], unique=False)
    op.alter_column('follow_requests', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    # ### end Alembic commands ###
