"""add_privacy_to_media

Revision ID: bf170faf7801
Revises: 075c2a5deb5a
Create Date: 2026-07-28 19:50:46.719032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf170faf7801'
down_revision: Union[str, None] = '075c2a5deb5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('privacy', sa.String(length=20), server_default='everyone', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'privacy')
    # ### end Alembic commands ###
