from typing import Optional
from uuid import UUID
from datetime import datetime
from pydantic import BaseModel, Field, field_validator

# The set of engagement events the tracking system collects.
ALLOWED_EVENT_TYPES = {
    "impression",
    "view_start",
    "watch_time",
    "view_percentage",
    "completion",
    "skip",
    "replay",
    "like",
    "comment",
    "share",
    "save",
    "follow_after_view",
    "not_interested",
    "report",
}

# Polymorphic content kinds the tracking system can reference.
ALLOWED_CONTENT_TYPES = {
    "video",
    "reel",
    "post",
    "story",
    "live",
    "media",
}


class EventTrackItem(BaseModel):
    """A single tracked event as reported by the client."""

    client_event_id: Optional[str] = Field(
        default=None,
        max_length=64,
        description="Idempotency token generated by the client so retries never double count.",
    )
    content_type: str = Field(..., max_length=20)
    content_id: UUID
    creator_id: Optional[UUID] = Field(
        default=None,
        description="Denormalized owner of the content (used for follow-after-view and creator analytics).",
    )
    event_type: str = Field(..., max_length=30)
    view_session_id: Optional[UUID] = Field(
        default=None,
        description="Correlation id grouping view_start / watch_time / view_percentage / completion.",
    )
    value: Optional[float] = Field(
        default=None,
        description="E.g. watch_time -> seconds, view_percentage -> 0-100.",
    )
    position_seconds: Optional[float] = Field(
        default=None,
        ge=0,
        description="Playback position where the event fired.",
    )
    context: Optional[str] = Field(default=None, max_length=50)
    source: Optional[str] = Field(default=None, max_length=50)
    metadata: Optional[dict] = Field(default=None, description="Free-form extra context (device, screen, ab test, etc.).")
    occurred_at: Optional[datetime] = Field(default=None, description="Client-reported event time; server time used if omitted.")

    @field_validator("content_type")
    def _validate_content_type(cls, v: str) -> str:
        v = v.lower()
        if v not in ALLOWED_CONTENT_TYPES:
            raise ValueError(
                f"Unsupported content_type '{v}'. Allowed: {sorted(ALLOWED_CONTENT_TYPES)}"
            )
        return v

    @field_validator("event_type")
    def _validate_event_type(cls, v: str) -> str:
        v = v.lower()
        if v not in ALLOWED_EVENT_TYPES:
            raise ValueError(
                f"Unsupported event_type '{v}'. Allowed: {sorted(ALLOWED_EVENT_TYPES)}"
            )
        return v


class EventTrackRequest(BaseModel):
    events: list[EventTrackItem] = Field(
        ...,
        min_length=1,
        max_length=200,
        description="Batch of up to 200 events for a single bulk ingestion.",
    )


class EventTrackResponse(BaseModel):
    received: int
    duplicates: int
    invalid: int = 0